project: hello-spai
description: Template for testing SPAI
thumbnail: https://play.google.com/store/apps/details?id=com.hellomagazine.hellomagazine&hl=es_US
scripts:
  - name: hello
apis:
  - name: hello
    port: 8010
uis:
  - name: hello
    port: 80
    # command: streamlit run uis/hello/main.py --server.address localhost # local
    command: streamlit run main.py --server.address 0.0.0.0 --server.port 80 # cloud
notebooks:
  - name: hello
